---

- hosts: 127.0.0.1
  connection: local
  gather_facts: yes

  vars:
    ec2_instance_region: "us-east-1"

  tasks:
    - name: Debug print of account keys.
      debug:
        msg: "{{ item }}"
        verbosity: 4
      loop:
        - " secret access key: {{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        - " access key: {{ lookup('env','AWS_ACCESS_KEY_ID') }}"
